# Generated by Django 3.1.1 on 2020-09-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200911_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-products'),
            preserve_default=False,
        ),
    ]
